### ISSUE TITLE
implant.py error decode

### ISSUE THREAD

**Issue by ghost** [1modm/stegator#1]
hi , thanks for this project , i have a problem  that when i execute the backdoor implant it gives me error decoding!!!

**Comment by 1modm** [comment]
Hi,

Take a look into the README.md, you need first a Cloudinary account.

This repository contains two files:
- stegator.py
- implant.py

In both files, you need to edit the access token part and add the ones that you previously generated:

cloudinary.config( 
  cloud_name = "xxxxxxxxxxxx", 
  api_key = "xxxxxxxxxxxx", 
  api_secret = "xxxxxxxxxxxx" 
)

Thanks

**Comment by ghost** [comment]
yes of course i did it but , i've the same problem !!

**Comment by 1modm** [comment]
Try the last revision of the files, I have updated the exception code to show the root error.

**Comment by ghost** [comment]
i try the last version of the files, when i launch the backdoor implant, it gives me error decoding error 2 the system cannot find the file specified!!

**Comment by 1modm** [comment]
Hi,

First of all I recommend you when log an issue to provide as much as details as possible.

I think that I have found the root cause of the issue, I have detected that you are running the backdoor in windows (I recommend you to use a better OS like linux :+1: ). And the error message "error 2 the system cannot find the file specified" means that the backdoor is not able to find the tool used to insert the messages into the images: http://steghide.sourceforge.net/

So to fix the issue you need to add steghide into the global path or copy the executable steghide.exe in the same folder as the backdoor.

Thanks
